import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactQueryProvider } from './providers/ReactQueryProvider';
import { NextUIProviderComponent } from './providers/NextUIProviderComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <NextUIProviderComponent>{children}</NextUIProviderComponent>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
